language: python
python:
  - "3.4"
install:
  - virtualenv ~/flexget/
  - cd ~/flexget
  - bin/pip install flexget
script:
  - cd $HOME/flexgen
  - mkdir -p $HOME/.config/flexget
  - ./flexgen > $HOME/.config/flexget/config.yml
  - ~/flexget/bin/flexget check

