language: python
python:
  - "3.4"
install:
  - virtualenv $HOME/flexget/
  - cd $HOME/flexget
  - bin/pip install flexget
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - mkdir -p $HOME/TVShows
script:
  - mkdir -p $HOME/.config/flexget
  - ./flexgen > $HOME/.config/flexget/config.yml
  - $HOME/flexget/bin/flexget check

