#!/usr/bin/env python3
#
# flexgen generates sophisticated FlexGet configuration for a given list of TV shows
#
# Copyright (c) 2014 Ondra Pelech
# license GPL-3.0+
#
# https://github.com/sideeffffect/flexgen
#

import urllib.parse
import re
import yaml
import functools
import os
import sys
import datetime

exactSubsMatch = True
seeds = 5
timedeltadays = 30
reject = sorted([ "1080i"
                , "720i"
                , "season"
                , "trailer"
                , "screener"
                , "TS"
                , "Cam"
                , "RAW"
                , "R5"
                , "WEBSCR"
                , "WEBsct"
                , "3D"
                , "VOSTFR"
                , "HEVC"
                , "h265"
                , "x265"
                ])
content_require = sorted(["*.mkv", "*.mp4"])
content_reject = sorted(["*password*", "*.avi", "*.wmv", "*.mpg", "*.r0*", "*.part0*"])
free_space = 20000
require_field = sorted(["quality", "tvdb_id", "tvdb_series_name", "tvdb_ep_id"])
reject_for = "90 minutes"
domain_delay = "5 seconds"
destination = "~/TVShows"
kickassServersIndex = 5
kickassServers = [
("https://", "kickass.to"),
("http://" , "katproxy.com"),
("https://", "kickass.to.prx.websiteproxy.co.uk"),
("http://", "kickass.so")
, ("https://", "kat.cr")
, ("https://", "zooqle.com")
]
domains = sorted([
"tracker.openbittorrent.com",
"tracker.publicbt.com",
"tracker.istole.it"
] + [ks[1] for ks in kickassServers])
trackers = sorted([
"udp://tracker.openbittorrent.com:80/announce",
"udp://tracker.publicbt.com:80/announce",
"udp://tracker.istole.it:80/announce"
])

qualities = [("1080p", 1), ("720p", 2), ("", 5)]
kickass_feed = "{0}{1}/search?q={2}+{3}+{5}+after%3A" + str(timedeltadays) + "+category%3ATV&fmt=rss"

confdoc = """# flexgen config file
# https://github.com/sideeffffect/flexgen
#
# shows                list of shows
#                      put here the names of the TV shows that you want to be torrenting
#                      names should adhere to http://thetvdb.com/
#
# waitForQuality       the video quality to wait for
#                      OPTIONAL, default: 1080p
#                      http://flexget.com/Plugins/quality
#
# waitingTime          time to wait before resorting to a worse quality video
#                      OPTIONAL, default: 6 days
#                      http://flexget.com/Plugins/series/timeframe
#
# subtitleLanguage     language for subtitles to download
#                      OPTIONAL, default: eng
#                      https://en.wikipedia.org/wiki/ISO_639-3
#
# email                specify parameters for sending notifications via email
#                      OPTIONAL, fields: from, to, smtp_host, smtp_port, smtp_username, smtp_password, ...
#                      http://flexget.com/Plugins/email
#

"""

confDictDefault = { 'shows': [ "Pioneer One"
                             , "My Favorite Show"
                             , "Another TV Show"
                             ]
                  , 'waitForQuality': "1080p"
                  , 'waitingTime': "6 days"
                  , 'subtitleLanguage': "eng"
                  }

configFileName = os.path.expanduser("~/.config/flexgen.yml")

def writeConfig(conf):
  configfile = open(configFileName, 'w')
  configfile.write(confdoc)
  configfile.write(yaml.dump(conf, default_flow_style=False, width=99999999))
  configfile.write("\n")
  configfile.close()

if not os.path.exists(os.path.expanduser("~/.config")):
  sys.stderr.write(os.path.expanduser("~/.config directory does not exist, creating it\n"))
  os.mkdir(os.path.expanduser("~/.config"))
if not os.path.exists(configFileName):
  sys.stderr.write("flexgen config file does not exist, writing default configuration to {0}\n".format(configFileName))
  writeConfig(confDictDefault)

def handleBadFormat():
  sys.stderr.write("Wrong format of {0}, renaming it...\n".format(configFileName))
  os.rename(configFileName,
            "{0}.{1}".format(configFileName, datetime.datetime.today().strftime("%Y_%m_%d__%H_%M_%S")))
  writeConfig(confDictDefault)
  confdictread = dict()

configFileHandle = open(configFileName, 'r')
confdictread = dict()
try:
  confdictread = yaml.load(configFileHandle)
except yaml.parser.ParserError:
  handleBadFormat()
if confdictread is None:
  handleBadFormat()

def unify(d1, d2):
  return dict(list(d1.items()) + list(d2.items()))

confdict = unify(confDictDefault, confdictread)

def isWrong(item, ty, reqLen):
  return (type(confdict[item]) is not ty) or reqLen(len(confdict[item]))

def overrideWrong(item, ty, reqLen):
  if isWrong(item, ty, reqLen):
    confdict[item] = confDictDefault[item]

overrideWrong('waitForQuality', str, lambda x: x < 1)
overrideWrong('waitingTime', str, lambda x: x < 1)
overrideWrong('subtitleLanguage', str, lambda x: x != 3)
overrideWrong('shows', list, lambda x: x < 1)

confdict['shows'] = sorted([show.title() for show in list(set([show.lower() for show in confdict['shows']]))])

templates = {
  'templates': {
    'global': {
      'series': {
        'defaultGroup': confdict['shows'],
        'settings': {
          'defaultGroup': {
            'quality': '!1080i !720i',
            'target': confdict['waitForQuality'],
            'timeframe': confdict['waitingTime']
          }
        },
        'identified_by': ['ep']
      },
      'free_space': {
        'path': "/home",
        'space': free_space
      },
      'content_filter': {
        'require': content_require,
        'reject': content_reject
      },
      'regexp': {
        'reject': [{"\\b{0}\\b".format(r) : {'from': 'title'}} for r in reject]
      },
      'require_field': require_field,
      'content_size': {
        'min': 10,
        'max': 10000,
        'strict': False
      },
      'if': [
        {"(tvdb_ep_air_date is not None) and (tvdb_ep_air_date < now - timedelta(days={0}))".format(timedeltadays): 'reject'}
      ],
      'pathscrub': "windows",
      'magnets': False,
      'add_trackers': trackers,
      'torrent_alive': {
        'min_seeds': seeds,
        'reject_for': reject_for
      },
      'thetvdb_lookup': True,
      'deluge': {
        'content_filename':
          '{{  tvdb_series_name | replace("/", " - ") | replace(";", ",")                                   }}/'
          'S{{ tvdb_season      | replace("/", " - ") | replace(";", ",") | pad(2)                          }}/'
          'S{{ tvdb_season      | replace("/", " - ") | replace(";", ",") | pad(2)                          }}'
          'E{{ tvdb_episode     | replace("/", " - ") | replace(";", ",") | pad(2)                          }} - '
          '{{  tvdb_ep_name     | replace("/", " - ") | replace(";", ",") | default("Unknown episode name") }} - '
          '{{  quality          | replace("/", " - ") | replace(";", ",")                                   }}',
        'main_file_only': True,
        'path': destination,
        'movedone': destination
      },
      'domain_delay': {
        d: domain_delay for d in domains
      }
    }
  }
}

email = {
  'subject': '[FlexgetTask] {% set comma = joiner(", ") %}{% for entry in task.accepted %}{{ comma() }}{{ entry.tvdb_series_name }} - {{ entry.tvdb_ep_id }} - {{ entry.quality }}{% endfor %}'
}

tasks_static = {
  '3_ThePirateBay_HD_Top': {
    'rss': "https://thepiratebay.org/rss/top100/208",
    'priority': 3,
    'verify_ssl_certificates': False
  },
  '4_ThePirateBay_HD': {
    'rss': "https://thepiratebay.org/rss/new/208",
    'priority': 4,
    'verify_ssl_certificates': False
  },
  '6_ThePirateBay_TOP': {
    'rss': "https://thepiratebay.org/rss/top100/205",
    'priority': 6,
    'verify_ssl_certificates': False
  },
  '6_EZRSS': {
    'rss': "https://eztv.ag/ezrss.xml",
    'priority': 6,
    'verify_ssl_certificates': False
  },
  '7_ExtraTorrent': {
    'rss': "http://extratorrent.cc/rss.xml?type=today&cid=8",
    'priority': 7,
    'verify_ssl_certificates': False
  },
  '7_ThePirateBay': {
    'rss': "https://thepiratebay.org/rss/new/205",
    'priority': 7,
    'verify_ssl_certificates': False
  },
  '7_RARBG': {
    'rss': "https://rarbg.to/rss.php",
    'priority': 7,
    'verify_ssl_certificates': False
  },
  '9_SubtitleDownload': {
    'priority': 9,
    'template': "no_global",
    'disable': "builtins",
    'filesystem': {
      'path': [destination],
      'regexp': ".*\.(mkv|mp4|m4v)$",
      'recursive': True
    },
    'accept_all': True,
    'subliminal': {
      'languages': [confdict['subtitleLanguage']],
      'alternatives': ["eng"],
      'exact_match': exactSubsMatch
    }
  }
}

def qtype(quality):
  if quality == "":
    return "TV"
  else:
    return quality

def genTask(show, quality, priority):
  return {
    '{0}_{1}_{2}'.format(priority, qtype(quality), re.sub(r'\s', '', show)): {
      'rss': kickass_feed.format( kickassServers[kickassServersIndex][0]
                                , kickassServers[kickassServersIndex][1]
                                , urllib.parse.quote(show)
                                , quality
                                , seeds
                                , urllib.parse.quote(''.join([" -" + x for x in reject]))
                                ),
      'priority': priority
      , 'verify_ssl_certificates': False
    }
  }

tasks_dynamic = functools.reduce(unify, [genTask(show, quality[0], quality[1]) for show in confdict['shows'] for quality in qualities])

tasks = {
  'tasks' : unify(tasks_static, tasks_dynamic)
}

config = unify(templates, tasks)


if 'email' in confdict:
  config['templates']['global']['email'] = unify(email, confdict['email'])
else:
  sys.stderr.write("Not using email.\n")


print(yaml.dump(config, default_flow_style=False, width=99999999))

if not os.path.exists(os.path.expanduser(destination)):
  os.mkdir(os.path.expanduser(destination))

